services:
  db:
    image: postgres:16-alpine
    container_name: zenpay_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: zenpay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: zenpay_queue
    ports:
      - "5672:5672"   # RabbitMQ port pro komunikaci
      - "15672:15672" # Management UI (webové rozhraní)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
